# Generated by Django 5.2.5 on 2025-09-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_comment_repository_link_alter_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repository_link',
            field=models.URLField(blank=True),
        ),
    ]
