# Generated by Django 5.2.5 on 2025-08-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_project_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
