# Generated by Django 5.2.5 on 2025-08-14 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 14, 18, 5, 50, 192970)),
        ),
    ]
