# Generated by Django 5.2.5 on 2025-08-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_project_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='timestamp',
            field=models.DateTimeField(editable=False),
        ),
    ]
