# Generated by Django 5.2.5 on 2025-08-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_project_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='project',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
